# Generated by Django 3.0.3 on 2020-03-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outback.Place'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outback.Place'),
        ),
    ]
