# Generated by Django 3.0.3 on 2020-03-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outback', '0002_auto_20200303_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='exits',
        ),
    ]
